/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wagwaan.setup;

import wagwaan.config.AMSUtility;
import wagwaan.config.ConnectionDB;
import wagwaan.config.SQLHelper;
import wagwaan.config.TableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author maurice
 */
public class StaffRegisterIntfr extends javax.swing.JInternalFrame {

    /**
     * Creates new form StaffRegisterIntfr
     */
    Connection con;
    public StaffRegisterIntfr() {
        initComponents();
        con=ConnectionDB.getInstance().getCon();
        btnupdate.setVisible(false);
        jLabel14.setVisible(false);
        jPasswordField1.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSearchDialog21 = new javax.swing.JDialog();
        jSearchPanel21 = new javax.swing.JPanel();
        jTextField1131 = new javax.swing.JTextField();
        jSearchScrollPane21 = new javax.swing.JScrollPane();
        jSearchTable21 = new javax.swing.JTable();
        jButton521 = new javax.swing.JButton();
        jSearchDialog22 = new javax.swing.JDialog();
        jSearchPanel22 = new javax.swing.JPanel();
        jTextField1132 = new javax.swing.JTextField();
        jSearchScrollPane22 = new javax.swing.JScrollPane();
        jSearchTable22 = new javax.swing.JTable();
        jButton522 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtidno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        combogender = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtkinnames = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtkinphoneno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnreset = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtdesignation = new javax.swing.JTextField();
        jPanel41 = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();
        jPanel42 = new javax.swing.JPanel();
        txtdeptid = new javax.swing.JTextField();
        searchButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        dateChooserField1 = new kiwi.ui.DateChooserField("dd-MM-yyyy");
        ;
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        dateChooserField2 = new kiwi.ui.DateChooserField("dd-MM-yyyy");
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();

        jSearchDialog21.setModal(true);
        jSearchDialog21.setUndecorated(true);
        jSearchDialog21.getContentPane().setLayout(new java.awt.GridBagLayout());

        jSearchPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSearchPanel21.setLayout(new java.awt.GridBagLayout());

        jTextField1131.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1131CaretUpdate(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jSearchPanel21.add(jTextField1131, gridBagConstraints);

        jSearchTable21.setToolTipText("");
        jSearchTable21.setShowHorizontalLines(false);
        /*javax.swing.table.TableColumn column = null;

        for (int i = 0; i < 4; i++) {

            column = jSearchTable2.getColumnModel().getColumn(i);

            if (i == 1) {

                column.setPreferredWidth(400);
                //sport column is bigger
            } else {

                column.setPreferredWidth(200);

            }
        }
        */
        jSearchTable21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchTable21MouseClicked(evt);
            }
        });
        jSearchScrollPane21.setViewportView(jSearchTable21);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        jSearchPanel21.add(jSearchScrollPane21, gridBagConstraints);

        jButton521.setText("Close");
        jButton521.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton521ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jSearchPanel21.add(jButton521, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jSearchDialog21.getContentPane().add(jSearchPanel21, gridBagConstraints);

        jSearchDialog22.setModal(true);
        jSearchDialog22.setUndecorated(true);
        jSearchDialog22.getContentPane().setLayout(new java.awt.GridBagLayout());

        jSearchPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSearchPanel22.setLayout(new java.awt.GridBagLayout());

        jTextField1132.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1132CaretUpdate(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jSearchPanel22.add(jTextField1132, gridBagConstraints);

        jSearchTable22.setToolTipText("");
        jSearchTable22.setShowHorizontalLines(false);
        /*javax.swing.table.TableColumn column = null;

        for (int i = 0; i < 4; i++) {

            column = jSearchTable2.getColumnModel().getColumn(i);

            if (i == 1) {

                column.setPreferredWidth(400);
                //sport column is bigger
            } else {

                column.setPreferredWidth(200);

            }
        }
        */
        jSearchTable22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchTable22MouseClicked(evt);
            }
        });
        jSearchScrollPane22.setViewportView(jSearchTable22);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        jSearchPanel22.add(jSearchScrollPane22, gridBagConstraints);

        jButton522.setText("Close");
        jButton522.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton522ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jSearchPanel22.add(jButton522, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jSearchDialog22.getContentPane().add(jSearchPanel22, gridBagConstraints);

        setClosable(true);
        setIconifiable(true);
        setTitle("STAFF REGISTER");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Staff ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Middle Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(txtfname, gridBagConstraints);

        jLabel5.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(txtlname, gridBagConstraints);

        jLabel6.setText("National ID No.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        txtidno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidnoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(txtidno, gridBagConstraints);

        jLabel7.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        combogender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MALE", "FEMALE" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(combogender, gridBagConstraints);

        jLabel8.setText("Telephone No.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        txtphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtphonenoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(txtphoneno, gridBagConstraints);

        jLabel9.setText("Next of Kin Names");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(txtkinnames, gridBagConstraints);

        jLabel10.setText("Next of Kin Phone No.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        txtkinphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkinphonenoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(txtkinphoneno, gridBagConstraints);

        jLabel11.setText("Department Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(txtmname, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(btnreset, gridBagConstraints);

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(btnsave, gridBagConstraints);

        btnclose.setText("CLOSE");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(btnclose, gridBagConstraints);

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(btnupdate, gridBagConstraints);

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(btnedit, gridBagConstraints);

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 2.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel1.setText("Designation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(txtdesignation, gridBagConstraints);

        jPanel41.setLayout(new java.awt.GridBagLayout());

        txtid.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel41.add(txtid, gridBagConstraints);

        searchButton1.setToolTipText("Search");
        searchButton1.setMaximumSize(new java.awt.Dimension(74, 53));
        searchButton1.setMinimumSize(new java.awt.Dimension(20, 20));
        searchButton1.setPreferredSize(new java.awt.Dimension(20, 20));
        searchButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel41.add(searchButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jPanel41, gridBagConstraints);

        jPanel42.setLayout(new java.awt.GridBagLayout());

        txtdeptid.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel42.add(txtdeptid, gridBagConstraints);

        searchButton2.setToolTipText("Search");
        searchButton2.setMaximumSize(new java.awt.Dimension(74, 53));
        searchButton2.setMinimumSize(new java.awt.Dimension(20, 20));
        searchButton2.setPreferredSize(new java.awt.Dimension(20, 20));
        searchButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel42.add(searchButton2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jPanel42, gridBagConstraints);

        jLabel12.setText("Date of Birth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(dateChooserField1, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("New");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jRadioButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Existing");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jRadioButton2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 2.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        jLabel13.setText("Employment Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel13, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(dateChooserField2, gridBagConstraints);

        jPasswordField1.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jPasswordField1, gridBagConstraints);

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Enter Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel1.add(jLabel14, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        AMSUtility.showSearchDialog(txtid, jSearchDialog21);
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void searchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton2ActionPerformed
        AMSUtility.showSearchDialog(txtdeptid, jSearchDialog22);
    }//GEN-LAST:event_searchButton2ActionPerformed

    private void jTextField1131CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1131CaretUpdate
        if(jTextField1131.getCaretPosition()>3){
                if(jRadioButton2.isSelected()){
                jSearchTable21.setModel(TableModel.createTableVectors(con, "select staff_id, first_name, middle_name, last_name from staff_registration where first_name ||' '||middle_name ||' '||last_name ilike '%"+jTextField1131.getText()+"%' and active=true"));
                jSearchScrollPane21.setViewportView(jSearchTable21);
                }
        }
    }//GEN-LAST:event_jTextField1131CaretUpdate

    private void jSearchTable21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchTable21MouseClicked
        txtid.setText(jSearchTable21.getValueAt(jSearchTable21.getSelectedRow(), 0).toString());
        txtfname.setText(jSearchTable21.getValueAt(jSearchTable21.getSelectedRow(), 1).toString());
        txtmname.setText(jSearchTable21.getValueAt(jSearchTable21.getSelectedRow(), 2).toString());
        txtlname.setText(jSearchTable21.getValueAt(jSearchTable21.getSelectedRow(), 3).toString());
        jSearchDialog21.dispose();
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        Date dob_date, adm_date;
        
        try {
            Statement st1=con.createStatement();
            ResultSet rs=st1.executeQuery("SELECT national_id, phone_no, nextof_kin_names, nextof_kin_phoneno, department_id, designation, dob, gender, employment_date  FROM staff_registration where staff_id='"+jSearchTable21.getValueAt(jSearchTable21.getSelectedRow(), 0).toString()+"' and active=true");
            while(rs.next()){
                dob_date=df.parse(rs.getObject(7).toString());
                dateChooserField1.setDate(dob_date);
                adm_date=df.parse(rs.getObject(9).toString());
                dateChooserField2.setDate(adm_date);
                combogender.setSelectedItem(rs.getObject(8));
                txtidno.setText(rs.getString(1));
                txtphoneno.setText(rs.getString(2));
                txtkinnames.setText(rs.getString(3));
                txtkinphoneno.setText(rs.getString(4));
                txtdeptid.setText(rs.getString(5));
                txtdesignation.setText(rs.getString(6));
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentRegisterIntfr.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(StudentRegisterIntfr.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jSearchTable21MouseClicked

    private void jButton521ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton521ActionPerformed
        jSearchDialog21.dispose();      // Add your handling code here:
    }//GEN-LAST:event_jButton521ActionPerformed

    private void jTextField1132CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1132CaretUpdate
        if(jTextField1132.getCaretPosition()>3){
            
                jSearchTable22.setModel(TableModel.createTableVectors(con, "select department_id, department_name from departments where department_name ilike '%"+jTextField1132.getText()+"%' "));
                jSearchScrollPane22.setViewportView(jSearchTable22);
            
        }
    }//GEN-LAST:event_jTextField1132CaretUpdate

    private void jSearchTable22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchTable22MouseClicked
        txtdeptid.setText(jSearchTable22.getValueAt(jSearchTable22.getSelectedRow(), 0).toString());
        
        jSearchDialog22.dispose();
        

    }//GEN-LAST:event_jSearchTable22MouseClicked

    private void jButton522ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton522ActionPerformed
        jSearchDialog22.dispose();      // Add your handling code here:
    }//GEN-LAST:event_jButton522ActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed
    private void validateSavedData(){
//    if(txtid.getText().isEmpty()){
//    JOptionPane.showMessageDialog(this, "Please input the staff id");
//    return;
//    }
    if(txtfname.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "Please input the first name");
    return;
    }
    if(txtmname.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "Please input the middle name");
    return;
    }
    if(txtlname.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "Please input the last name");
    return;
    }
    if(txtidno.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "Please input the staff's national ID no.");
    return;
    }
    if(combogender.getSelectedItem()==null){
    JOptionPane.showMessageDialog(this, "Please select the staff's gender");
    return;
    }
    if(dateChooserField1.getDate()==null){
    JOptionPane.showMessageDialog(this, "Please select the staff's DOB");
    return;
    }
    if(txtphoneno.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "Please input the phone no");
    return;
    }
    if(txtkinnames.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "Please input the next of kin's names");
    return;
    }
    if(txtkinphoneno.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "Please input the next of kin's phone no");
    return;
    }
    if(txtdeptid.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "please input the department id");
    return;
    }
    if(txtdesignation.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "Please input the staff's designation");
    return;
    }
    if(dateChooserField2.getDate()==null){
    JOptionPane.showMessageDialog(this, "Please select the employment date");
    return;
    }
    
    }
    
    
    private void insertDetails(){
    PreparedStatement pr=null;
    String sql="INSERT INTO staff_registration(staff_id, first_name, middle_name, last_name, national_id, phone_no, nextof_kin_names, "
            + "nextof_kin_phoneno, department_id, designation, dob, gender, employment_date)VALUES (?, ?, ?, ?, ?, ?,  ?, ?, ?, ?,  ?::date, ?, ?::date)";
        try {
            con.setAutoCommit(false);
            pr=con.prepareStatement(sql);
            pr.setString(1, getID());
            pr.setString(2, txtfname.getText());
            pr.setString(3, txtmname.getText());
            pr.setString(4, txtlname.getText());
            pr.setString(5, txtidno.getText());
            pr.setString(6, txtphoneno.getText());
            pr.setString(7, txtkinnames.getText());
            pr.setString(8, txtkinphoneno.getText());
            pr.setString(9, txtdeptid.getText());
            pr.setString(10, txtdesignation.getText());
            pr.setObject(11, dateChooserField1.getDate().toString());
            pr.setObject(12, combogender.getSelectedItem());
            pr.setObject(13, dateChooserField2.getDate().toString());
            pr.executeUpdate();
            con.commit();
            con.setAutoCommit(true);
            
            if(pr!=null){
            JOptionPane.showMessageDialog(this, "Insert is Successful");
            clearFields();
            }
            else{
            JOptionPane.showMessageDialog(this, "There is a problem");
            }
        } catch (SQLException ex) {
            Logger.getLogger(StaffRegisterIntfr.class.getName()).log(Level.SEVERE, null, ex);
        try {
            con.rollback();
        } catch (SQLException ex1) {
            Logger.getLogger(StaffRegisterIntfr.class.getName()).log(Level.SEVERE, null, ex1);
        }
        }
    }
    
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        validateSavedData();
        insertDetails();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
            if(jRadioButton1.isSelected()){
                btnupdate.setEnabled(false);
                btnedit.setEnabled(false);
                searchButton1.setEnabled(false);
                searchButton2.setEnabled(true);
//            txtid.setEditable(true);
            txtfname.setEditable(true);
            txtmname.setEditable(true);
            txtlname.setEditable(true);
            txtidno.setEditable(true);
            combogender.setEnabled(true);
            txtphoneno.setEditable(true);
            txtkinnames.setEditable(true);
            txtkinphoneno.setEditable(true);
//            txtdeptid.setEditable(true);
            txtdesignation.setEditable(true);
            btnsave.setEnabled(true);
            }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        if(jRadioButton2.isSelected()){
            btnupdate.setEnabled(true);
            txtid.setEditable(false);
            searchButton1.setEnabled(true);
            btnedit.setEnabled(true);
            btnsave.setEnabled(false);
            searchButton2.setEnabled(false);
            txtfname.setEditable(false);
            txtmname.setEditable(false);
            txtlname.setEditable(false);
            txtidno.setEditable(false);
            combogender.setEnabled(false);
            txtphoneno.setEditable(false);
            txtkinnames.setEditable(false);
            txtkinphoneno.setEditable(false);
//            txtdeptid.setEditable(false);
            txtdesignation.setEditable(false);
            }
    }//GEN-LAST:event_jRadioButton2ItemStateChanged
            private void clearFields(){
                txtid.setText("");
                buttonGroup1.clearSelection();
                jLabel14.setVisible(false);
                jPasswordField1.setVisible(false);
                txtfname.setText("");
                txtmname.setText("");
                txtlname.setText("");
                txtidno.setText("");
                combogender.setSelectedItem(null);
                dateChooserField1.setDate(null);
                dateChooserField2.setDate(null);
                txtphoneno.setText("");
                txtkinnames.setText("");
                txtkinphoneno.setText("");
                txtdeptid.setText("");
                txtdesignation.setText("");
            }
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        clearFields();
    }//GEN-LAST:event_btnresetActionPerformed
    private void updateDb(){
        
        PreparedStatement pr=null;
        String sql=null;
        int count=0;
        sql="select count(staff_id) from staff_registration where staff_id='"+txtid.getText()+"' ";
        try {
            con.setAutoCommit(false);
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()){
            count=rs.getInt(1);
            }
            if(count>0){
                validateSavedData();
            sql="UPDATE staff_registration   SET staff_id=?, first_name=?, middle_name=?, last_name=?, national_id=?, phone_no=?,"
                    + " nextof_kin_names=?, nextof_kin_phoneno=?, department_id=?, \n" +
"designation=?, dob=?::date, gender=?, employment_date=?::date WHERE staff_id='"+txtid.getText()+"' ";
            pr=con.prepareStatement(sql);
            pr.setString(1, txtid.getText());
            pr.setString(2, txtfname.getText());
            pr.setString(3, txtmname.getText());
            pr.setString(4, txtlname.getText());
            pr.setString(5, txtidno.getText());
            pr.setString(6, txtphoneno.getText());
            pr.setString(7, txtkinnames.getText());
            pr.setString(8, txtkinphoneno.getText());
            pr.setString(9, txtdeptid.getText());
            pr.setString(10, txtdesignation.getText());
            pr.setObject(11, dateChooserField1.getDate().toString());
            pr.setObject(12, combogender.getSelectedItem());
            pr.setObject(13, dateChooserField2.getDate().toString());
            pr.executeUpdate();
            con.commit();
            con.setAutoCommit(true);
            
            if(pr!=null){
                JOptionPane.showMessageDialog(this, "Update Successful");
                clearFields();
            }
            else{
                JOptionPane.showMessageDialog(this, "There is a problem");
            }
            }
            else{
            validateSavedData();
            insertDetails();
            }
        } catch (SQLException ex) {
            try {
                con.rollback();
            } catch (SQLException ex1) {
                Logger.getLogger(StaffRegisterIntfr.class.getName()).log(Level.SEVERE, null, ex1);
                JOptionPane.showMessageDialog(this, ex1.getMessage());
            }
            Logger.getLogger(StaffRegisterIntfr.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        validateSavedData();
        updateDb();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
                        this.btnedit.setVisible(false);
                        btnupdate.setVisible(true);
//                searchButton1.setEnabled(false);
            txtfname.setEditable(true);
            txtmname.setEditable(true);
            txtlname.setEditable(true);
            txtidno.setEditable(true);
            combogender.setEnabled(true);
            txtphoneno.setEditable(true);
            txtkinnames.setEditable(true);
            txtkinphoneno.setEditable(true);
//            txtdeptid.setEditable(true);
            txtdesignation.setEditable(true);
    }//GEN-LAST:event_btneditActionPerformed

    private void txtidnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidnoKeyReleased
        Character ch=evt.getKeyChar();
        if(!Character.isDigit(ch)){
        JOptionPane.showMessageDialog(this, "ID No. cannot have alphabets");
        txtidno.setText("");
        }
    }//GEN-LAST:event_txtidnoKeyReleased

    private void txtphonenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphonenoKeyReleased
        Character z=evt.getKeyChar();
        if(!Character.isDigit(z)){
        JOptionPane.showMessageDialog(this, "Phone No. cannot contain alphabets");
        txtphoneno.setText("");
        }
    }//GEN-LAST:event_txtphonenoKeyReleased

    private void txtkinphonenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkinphonenoKeyReleased
        Character z=evt.getKeyChar();
        if(!Character.isDigit(z)){
        JOptionPane.showMessageDialog(this, "Phone No. cannot contain alphabets");
        txtkinphoneno.setText("");
        }
    }//GEN-LAST:event_txtkinphonenoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int option=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete staff ID: "+txtid.getText()+"?\n. Please Note that all information relating to this staff will be deleted","Confirmation before Deletion!!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(option==JOptionPane.YES_OPTION){
         jLabel14.setVisible(true);
        jPasswordField1.setVisible(true);
        
       
       if(jPasswordField1.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Please input the password to delete the staff", "Missing info!!", JOptionPane.INFORMATION_MESSAGE);
           return;
       }
           
       if(!jPasswordField1.getText().equals("deletion2015")){
        JOptionPane.showMessageDialog(this, "Incorrect Password");
        return;
        }
       
        else{
            try {
                con.setAutoCommit(false);
                PreparedStatement pr=con.prepareStatement("delete from staff_registration where staff_id='"+txtid.getText()+"'");
                pr.executeUpdate();
                        con.commit();
                        con.setAutoCommit(true);
                if(pr!=null){
                JOptionPane.showMessageDialog(this, "Deletion was successful");
                clearFields();
                }
        
            } catch (SQLException ex) {
                Logger.getLogger(StaffRegisterIntfr.class.getName()).log(Level.SEVERE, null, ex);
                try {
                    con.rollback();
                } catch (SQLException ex1) {
                    Logger.getLogger(StaffRegisterIntfr.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
        }
        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
        public String getID(){
String id=null;
if(jRadioButton1.isSelected()){
        try {
            ResultSet rs=SQLHelper.getResultset(con, "SELECT 'STF'|| nextval('staff_id_seq')");
            while(rs.next()){
                id=rs.getString(1);
    }
        } catch (SQLException ex) { 
        }
    }
return id;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combogender;
    private kiwi.ui.DateChooserField dateChooserField1;
    private kiwi.ui.DateChooserField dateChooserField2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton521;
    private javax.swing.JButton jButton522;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JDialog jSearchDialog21;
    private javax.swing.JDialog jSearchDialog22;
    private javax.swing.JPanel jSearchPanel21;
    private javax.swing.JPanel jSearchPanel22;
    private javax.swing.JScrollPane jSearchScrollPane21;
    private javax.swing.JScrollPane jSearchScrollPane22;
    private javax.swing.JTable jSearchTable21;
    private javax.swing.JTable jSearchTable22;
    private javax.swing.JTextField jTextField1131;
    private javax.swing.JTextField jTextField1132;
    private javax.swing.JButton searchButton1;
    private javax.swing.JButton searchButton2;
    private javax.swing.JTextField txtdeptid;
    private javax.swing.JTextField txtdesignation;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidno;
    private javax.swing.JTextField txtkinnames;
    private javax.swing.JTextField txtkinphoneno;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtphoneno;
    // End of variables declaration//GEN-END:variables
}
